name: Food Admin Dashboard GitHub Actions
run-name: ${{ github.actor }} is running Food Admin Dashboard GitHub Actions 🚀

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier for Code Formatting
        run: npm run format

      - name: Run Dependency Check (OWASP Dependency-Check)
        uses: dependency-check/Dependency-Check_Action@1.1.0
        id: dependencyCheck
        with:
          project: "Food"
          path: "."
          format: "ALL"

      - name: Build the Application
        run: npm run build

  deploy:
    name: Deploy to Docker
    needs: build-setup
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERIMAGE_NAME: yashbansod2003/food_dashboard
      DOCKERIMAGE_TAG: build-${{ github.run_number }}
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: docker build -t ${{ env.DOCKERIMAGE_NAME }}:${{ env.DOCKERIMAGE_TAG }} -f docker/production/Dockerfile .
      - name: Push to DockerHub
        run: docker push ${{ env.DOCKERIMAGE_NAME }}:${{ env.DOCKERIMAGE_TAG }}
